import type { Metadata } from "next";
import { Inter, Ysabeau_SC } from "next/font/google";
import "./globals.css";
import { ScrollToTopButton } from "../../components/Buttons";
import { NavbarAlt } from "../../components/navigation/NavBar";
import Footer from "../../components/Footer";
import { SanityProvider } from "@/context/sanity";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const ysabeauSC = Ysabeau_SC({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${ysabeauSC.variable}`}>
      <body
        className={`${inter.className} antialiased overflow-x-hidden`}>
        <NavbarAlt />
        <SanityProvider>{children}</SanityProvider>
        <ScrollToTopButton />
        <Footer />
      </body>
    </html>
  );
}
